#!/bin/bash

MODEL="gemma3"

if [ -z "$1" ]; then
    read -p "input: " INPUT
else
    INPUT="$*"
fi

# call to the ollama server api to generate
curl -s http://localhost:11434/api/generate \
  -d '{
    "model": "'"$MODEL"'",
    "prompt": "'"$INPUT"'",
    "stream": false
  }' | jq -r .response



